version: '3.3'
services:
  db:
    container_name: pg.db
    image: postgres:10.3-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  api:
    container_name: reactivity-api
    image: app-reactivity-api
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    ports:
      - "7001:5000"
    depends_on:
      - db
    links:
      - db

  reverse-proxy:
    container_name: proxy-api
    image: nginx:1.17.8
    depends_on:
      - api
    ports:
      - "80:8080"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf        